project_id = "ypmkbrdymnfxxwoogpdb"

[functions.graph-api]
verify_jwt = false

[functions.ms-auth]
verify_jwt = false

[functions.classify-email]
verify_jwt = false

[functions.process-email-rules]
verify_jwt = false

[functions.process-entity-rules]
verify_jwt = false

[functions.extract-invoice]
verify_jwt = false

[functions.sync-outlook-tags]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.prepare-for-rules]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.webhook-ingest]
verify_jwt = false

[functions.prepare-webhook-for-rules]
verify_jwt = false

[functions.process-webhook-rules]
verify_jwt = false

[functions.classify-webhook-event]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.sync-webflow-forms]
verify_jwt = false

[functions.messaging-ingest]
verify_jwt = false
