project_id = "ypmkbrdymnfxxwoogpdb"

[functions.graph-api]
verify_jwt = false

[functions.ms-auth]
verify_jwt = false

[functions.classify-email]
verify_jwt = false

[functions.process-email-rules]
verify_jwt = false

[functions.process-entity-rules]
verify_jwt = false

[functions.extract-invoice]
verify_jwt = false

[functions.sync-outlook-tags]
verify_jwt = false

[functions.sync-emails]
verify_jwt = false

[functions.prepare-for-rules]
verify_jwt = false

[functions.send-invite]
verify_jwt = false
